
zello:
  network: kraaft # Your account name (<network>.zellowork.com)
  channel: test-poc # The Zello channel to listen to
  auth:
    # More info here: https://github.com/zelloptt/zello-channel-api/blob/master/AUTH.md
    dev_token: # Your Sample development token
    issuer: # Issuer
    private_key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCj6e7VKBrKb17d
      ...
      awstJOhSGCsYezIi7Thaajcee4pm0VT/cEJxB4QzMKilAys07mXq/xPvOmx1P9oM
      -----END PRIVATE KEY-----

trello:
  # More info here: https://developers.trello.com/docs/api-introduction#section--a-name-auth-authentication-and-authorization-a-
  api_key: # Your Trello API Key.
  api_token: # Your Trello API Token
  list_id: # Id of the list (a column in a board) in which the cards are created
